version: '3.6'
networks:
  #project name
  butik-kanina-house-uniform: {}

services:
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      #port nginx
      - ${HTTP_PORT:-8096}:80
    volumes:
      - ./nginx/nginx-njs.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/config/cors.conf:/etc/nginx/config/cors.conf:ro
      - ./nginx/route_${APP_ENV:-development}.conf:/etc/nginx/routes/butik-kanina-house-uniform.conf:ro
      - ./nginx/config/nginx-njs.js:/etc/nginx/javascript/nginx.js:ro
      - ./nginx/site-with-oauth2.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/www:/var/www/html:ro
      - ./cache/cdn:/opt/app/cache/cdn:ro
    networks:
      - butik-kanina-house-uniform

  postgres:
    image: postgres:9.5
    volumes:
      - ./cache/postgres:/var/lib/postgresql/data
    user: ${UID:-1000}:${GROUPS:-1000}
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASS:-postgres}
      - POSTGRES_DB=${DB_NAME:-postgres}
      - PGDATA=/var/lib/postgresql/data/data
    ports:
      - 5434:5432
    networks:
      #oauth2 naming follow line 4
      butik-kanina-house-uniform:
        aliases:
          - ${DB_HOST:-postgres}

  redis:
    image: redis
    volumes:
      - ./cache/redis:/data
    user: ${UID:-1000}:${GROUPS:-1000}
    networks:
      #oauth2 naming follow line 4
      butik-kanina-house-uniform:
        aliases:
          - ${REDIS_HOST:-redis}

  spring:
    image: maven:3-jdk-8
    # restart: unless-stopped
    working_dir: /opt/app
    volumes:
      - .:/opt/app
      - ./cache/maven:/var/maven/.m2
    ports:
      - 8000:8080
    user: ${UID:-1000}:${GROUPS:-1000}
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST:-postgres}:${DB_PORT:-5432}/${DB_NAME:-postgres}
      - SPRING_DATASOURCE_USERNAME=${DB_USER:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASS:-postgres}
      - SPRING_PROFILES_ACTIVE=${APP_ENV:-production}
      - SPRING_CACHE_TYPE=redis
      - SPRING_REDIS_HOST=${REDIS_HOST:-redis}
      - SPRING_REDIS_PORT=${REDIS_PORT:-6379}
      - SPRING_CACHE_REDIS_TIMETOLIVE=1
      - SECURITY_JWT_ENABLED=true
      - MAVEN_CONFIG=/var/maven/.m2
      - SERVER_SERVLET_CONTEXT_PATH=/
      - CDN_PATH=${CDN_PATH:-/opt/app/cache/cdn}
      - CDN_BASEURL=${CDN_BASEURL:-http://localhost:8080}
      - BASE_URL=${BASE_URL:-http://localhost:8080}
      - SPRING_MAIL_HOST=${SMTP_HOST}
      - SPRING_MAIL_PORT=${SMTP_PORT}
      - SPRING_MAIL_USERNAME=${SMTP_USERNAME}
      - SPRING_MAIL_PASSWORD=${SMTP_PASSWORD}
      - SPRING_MAIL_SENDER_NAME=${SMTP_SENDER_NAME}
      - SPRING_MAIL_SENDER_MAIL=${SMTP_SENDER_MAIL}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=${SMTP_AUTH}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE={SMTP_STARTTLS_ENABLE}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED={SMTP_STARTTLS_REQUIRED}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_SL_ENABLE={SMTP_SSL_ENABLE}

    networks:
      #oauth2 naming follow line 4
      butik-kanina-house-uniform:
        aliases:
          - oauth2.api
          - butik-kanina-house-uniform.api
    command: [ "mvn", "-Duser.home=/var/maven", "spring-boot:run" ]

  vue:
    image: node:14-alpine
    working_dir: /opt/app
    user: ${UID:-1000}:${GROUPS:-1000}
    volumes:
      - ./template:/opt/app
    command: [ "sh", "-c", "yarn install && yarn serve" ]
    networks:
      #oauth2 naming follow line 4
      butik-kanina-house-uniform:
        aliases:
          - vue